QuanLyNhanSu/Models/HopDong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyNhanSu.Models
{

using System;
    using System.Collections.Generic;
    
public partial class HopDong
{

    public HopDong()
    {

        this.NhanViens = new HashSet<NhanVien>();

    }


    public string MaHopDong { get; set; }

    public string LoaiHopDong { get; set; }

    public Nullable<System.DateTime> NgayBatDau { get; set; }

    public Nullable<System.DateTime> NgayKetThuc { get; set; }

    public string GhiChu { get; set; }

    public string MaNhanVien { get; set; }



    public virtual ICollection<NhanVien> NhanViens { get; set; }

    public virtual NhanVien NhanVien { get; set; }

}

}

QuanLyNhanSu/Areas/admin/Controllers/HopDongController.cs
using QuanLyNhanSu.Models;
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;
using System.IO;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class HopDongController : Controller
    {
        // GET: admin/HopDong
        public QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        public HopDongController()
        { 
            String session = System.Web.HttpContext.Current.Session["MaNhanVien"] as String;
            if (System.Web.HttpContext.Current.Session["MaNhanVien"] == null || session != "admin")
                {
                System.Web.HttpContext.Current.Response.Redirect("~/");
                }
        }
        // GET: HopDong
        public ActionResult Index()
        {
            var hopDongs = db.HopDongs.ToList();
            return View(hopDongs);
        }

        // GET: HopDong/Create
        public ActionResult Create()
        {
            var hopDong = new HopDong();
            var nhanViens = db.NhanViens.ToList();
            ViewBag.MaNhanVien = new SelectList(nhanViens, "MaNhanVien", "HoTen");
            return View(hopDong);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( HopDong hopDong)
        {
            if (ModelState.IsValid)
            {
                NhanVien nv = db.NhanViens.SingleOrDefault(n => n.MaNhanVien == hopDong.MaNhanVien);
                nv.MaHopDong = hopDong.MaHopDong;

                db.HopDongs.Add(hopDong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }



            return View(hopDong);
        }

        private void PopulateNhanVienDropDownList(HopDong hopDong)
        {
            var nhanViens = db.NhanViens.ToList();
            ViewBag.MaNhanVien = new SelectList(nhanViens, "MaNhanVien", "HoTen");
        }

        // GET: HopDong/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            HopDong hopDong = db.HopDongs.Find(id);
            if (hopDong == null)
            {
                return HttpNotFound();
            }
            var nhanViens = db.NhanViens.ToList();
            ViewBag.MaNhanVien = new SelectList(nhanViens, "MaNhanVien", "HoTen");
            var hoten= db.NhanViens.SingleOrDefault(n=>n.MaHopDong == id);
            ViewBag.hoten = hoten.HoTen;
            ViewBag.ma = hoten.MaNhanVien;
            return View(hopDong);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HopDong hopDong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hopDong).State = System.Data.Entity.EntityState.Modified;
                NhanVien nv = db.NhanViens.SingleOrDefault(n => n.MaNhanVien == hopDong.MaNhanVien);
                nv.MaHopDong = hopDong.MaHopDong;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateNhanVienDropDownList(hopDong);
            return View(hopDong);
        }

        // GET: HopDong/Delete/5
        public ActionResult Delete(string id)
        {
            HopDong hopDong = db.HopDongs.Find(id);
            if (hopDong == null)
            {
                return HttpNotFound();
            }
            return View(hopDong);
        }

        // POST: HopDong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HopDong hopDong = db.HopDongs.Find(id);
            
            db.HopDongs.Remove(hopDong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: HopDong/Extend/5
        public ActionResult Extend(string id)
        {
            HopDong hopDong = db.HopDongs.Find(id);
            if (hopDong == null)
            {
                return HttpNotFound();
            }
            return View(hopDong);
        }

        // POST: HopDong/Extend/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Extend(string id, DateTime newEndDate)
        {
            HopDong hopDong = db.HopDongs.Find(id);
            if (hopDong != null)
            {
                hopDong.NgayKetThuc = newEndDate;
                db.Entry(hopDong).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult XuatFileExel()
        {

            var ds = db.NhanViens.Where(n => n.MaNhanVien != "admin" && n.MaHopDong != null).ToList();
            var phong = db.PhongBans.ToList();
            var gv = new GridView();
            //===================================================
            DataTable dt = new DataTable();
            //Add Datacolumn
            DataColumn workCol = dt.Columns.Add("Mã hợp đồng", typeof(String));

            dt.Columns.Add("Loại hợp đồng", typeof(String));
            dt.Columns.Add("Ngày bắt đầu", typeof(String));
            dt.Columns.Add("Ngày kết thúc", typeof(String));
            dt.Columns.Add("Ghi chú", typeof(String));
            dt.Columns.Add("Mã nhân viên", typeof(String));
            dt.Columns.Add("Tên nhân viên", typeof(String));

            //Add in the datarow


            foreach (var item in ds)
            {
                DataRow newRow = dt.NewRow();
                newRow["Mã hợp đồng"] = item.HopDong.MaHopDong;
                newRow["Loại hợp đồng"] = item.HopDong.LoaiHopDong;
                newRow["Ngày bắt đầu"] = item.HopDong.NgayBatDau;
                newRow["Ngày kết thúc"] = item.HopDong.NgayKetThuc;
                newRow["Ghi chú"] = item.HopDong.GhiChu;
                newRow["Mã nhân viên"] = item.MaNhanVien;
                newRow["Tên nhân viên"] = item.HoTen;


                dt.Rows.Add(newRow);
            }

            //====================================================
            gv.DataSource = dt;
            // gv.DataSource = ds;
            gv.DataBind();

            Response.ClearContent();
            Response.Buffer = true;

            Response.AddHeader("content-disposition", "attachment; filename=danh-sach-hop-dong.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

            gv.RenderControl(objHtmlTextWriter);

            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return Redirect("/admin/HopDong");
        }
    }
}

QuanLyNhanSu/Areas/admin/Views/HopDong/Create.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
    QuanLyNhanSu.Models.QuanLyNhanSuEntities db = new QuanLyNhanSu.Models.QuanLyNhanSuEntities();
}
@model QuanLyNhanSu.Models.HopDong

<h2>Thêm Hợp Đồng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.MaHopDong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaHopDong, new { htmlAttributes = new { @class = "form-control", } })
            @Html.ValidationMessageFor(model => model.MaHopDong, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LoaiHopDong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LoaiHopDong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LoaiHopDong, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NgayBatDau, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NgayBatDau, new { @class = "form-control", type = "date", Value = DateTime.Now.ToString("dd/MM/yyyy") })
            @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayKetThuc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NgayKetThuc, new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.MaNhanVien, (SelectList)ViewBag.MaNhanVien, "-- Chọn Nhân Viên --", new { @class = "form-control", value = Model.MaNhanVien, @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.MaNhanVien, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyNhanSu/Areas/admin/Views/HopDong/Delete.cshtml
@model QuanLyNhanSu.Models.HopDong
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa hợp đồng</h2>

<div class="alert alert-danger">
    <h4>Bạn có chắc muốn hủy hợp đồng này không?</h4>
    <h5>Hủy hợp đồng sẽ hủy mọi thông tin về nhân viên và tài khoản</h5>
</div>

<div class="form-horizontal">
    <h4>Chi tiết hợp đồng:</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>Mã hợp đồng:</dt>
        <dd>@Model.MaHopDong</dd>

        <dt>Loại hợp đồng:</dt>
        <dd>@Model.LoaiHopDong</dd>

        <dt>Ngày bắt đầu:</dt>
        <dd>@Model.NgayBatDau.ToString()</dd>

        <dt>Ngày kết thúc:</dt>
        <dd>@Model.NgayKetThuc.ToString()</dd>

        <dt>Ghi chú:</dt>
        <dd>@Model.GhiChu</dd>
    </dl>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions">
        <input type="text" hidden name="id" value="@Model.MaHopDong" />
        <input type="submit" value="Hùy hợp đồng" class="btn btn-danger" />
        @Html.ActionLink("Hủy bỏ", "Index", null, new { @class = "btn btn-default" })
    </div>
}

QuanLyNhanSu/Areas/admin/Views/HopDong/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
    QuanLyNhanSu.Models.QuanLyNhanSuEntities db = new QuanLyNhanSu.Models.QuanLyNhanSuEntities();
}
@model QuanLyNhanSu.Models.HopDong

<h2>Chỉnh sửa Hợp Đồng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.MaHopDong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaHopDong, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.MaHopDong, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LoaiHopDong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LoaiHopDong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LoaiHopDong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayBatDau, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NgayBatDau, new { @class = "form-control", type = "text", value = Model.NgayBatDau.ToString(), @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayKetThuc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NgayKetThuc, new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Nhân Viên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class=" form-control" type="text" value="@ViewBag.hoten" readonly />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="text" hidden name="MaNhanVien" value="@ViewBag.ma" />
            <input type="submit" value="Lưu thay đổi" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $(document).ready(function () {
        $(".datepicker").datepicker();
    });
</script>

QuanLyNhanSu/Areas/admin/Views/HopDong/Extend.cshtml
@model QuanLyNhanSu.Models.HopDong

@{
    ViewBag.Title = "Extend";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Gia Hạn Hợp Đồng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.MaHopDong, "Mã Hợp Đồng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p>@Model.MaHopDong</p>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ngày Kết Thúc Mới", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="newEndDate" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gia Hạn" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

QuanLyNhanSu/Areas/admin/Views/HopDong/Index.cshtml
@model IEnumerable<QuanLyNhanSu.Models.HopDong>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
    QuanLyNhanSu.Models.QuanLyNhanSuEntities db = new QuanLyNhanSu.Models.QuanLyNhanSuEntities();

}

<div class="">
    <div class="">
        <h1 class="page-header">
            Quản lý hợp đồng
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Hợp đồng
            </li>
        </ol>
    </div>
</div>

<a class="btn btn-primary " href="@Url.Action("XuatFileExel", "HopDong")">
    Xuất danh sách hợp đồng
</a>
<hr />
@if (Model == null)
{
    <div class="alert alert-warning">
        Không có hợp đồng nào để hiển thị.
    </div>
}
else
{

    <div class="table-responsive">
        <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
            <thead>
                <tr class="success">
                    <th>Mã Hợp Đồng</th>
                    <th>Loại Hợp Đồng</th>
                    <th>Ngày Bắt Đầu</th>
                    <th>Ngày Kết Thúc</th>
                    <th>Ghi Chú</th>
                    <th>Mã Nhân Viên</th>
                    <th>Tên Nhân Viên</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaHopDong</td>
                        <td>@item.LoaiHopDong</td>
                        <td>@item.NgayBatDau</td>
                        <td>@item.NgayKetThuc</td>
                        <td>@item.GhiChu</td>
                        <td>@item.MaHopDong</td>
                        <td>@db.NhanViens.Where(h => h.MaNhanVien != "admin").SingleOrDefault(n => n.MaHopDong == item.MaHopDong).HoTen</td>

                        <td>
                            @Html.ActionLink("Sửa", "Edit", new { id = item.MaHopDong }, new { @class = "btn btn-primary" }) |
                            @Html.ActionLink("Gia Hạn", "Extend", new { id = item.MaHopDong }, new { @class = "btn btn-warning" }) |
                            @Html.ActionLink("Hủy hợp đồng", "Delete", new { id = item.MaHopDong }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}