QuanLyNhanSu/Areas/admin/Controllers/QuanLyChuyenNganhController.cs
using QuanLyNhanSu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class QuanLyChuyenNganhController : AuthorController
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();

        // GET: admin/QuanLyChuyenNganh
        public ActionResult Index()
        {
            var chuyenNganhList = db.ChuyenNganhs.ToList();
            return View(chuyenNganhList);
        }

        // GET: ChuyenNganh/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ChuyenNganh chuyenNganh)
        {
            if (ModelState.IsValid)
            {
                db.ChuyenNganhs.Add(chuyenNganh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chuyenNganh);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var chuyenNganh = db.ChuyenNganhs.Find(id);
            if (chuyenNganh == null)
            {
                return HttpNotFound("Record not found");
            }
            return View(chuyenNganh);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ChuyenNganh cn)
        {
            if (ModelState.IsValid)
            {
                var existingChuyenNganh = db.ChuyenNganhs.Find(cn.MaChuyenNganh);
                if (existingChuyenNganh != null)
                {
                    existingChuyenNganh.TenChuyenNganh = cn.TenChuyenNganh;
                    db.SaveChanges();
                    return Redirect("/admin/QuanLyChuyenNganh");
                }
                return HttpNotFound("Record not found");
            }
            return View(cn);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            var chuyenNganh = db.ChuyenNganhs.SingleOrDefault(cn => cn.MaChuyenNganh == id);
            if (chuyenNganh == null)
            {
                return HttpNotFound();
            }
            return View(chuyenNganh);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var chuyenNganh = db.ChuyenNganhs.SingleOrDefault(cn => cn.MaChuyenNganh == id);
            db.ChuyenNganhs.Remove(chuyenNganh);
            db.SaveChanges();
            return Redirect("/admin/QuanLyChuyenNganh");
        }

        public ActionResult FindEmployees(string id)
        {
            var employees = db.NhanViens.Where(nv => nv.MaChuyenNganh == id).ToList();
            var tencn = db.ChuyenNganhs.Find(id).TenChuyenNganh;
            ViewBag.tencn = tencn;
            return View(employees);
        }
        [HttpGet]
        public ActionResult EditChuyenNganhNV(String id)
        {
            var user = db.NhanViens.Where(n => n.MaNhanVien == id).FirstOrDefault();
            UserValidate userVal = new UserValidate();

            userVal.MaNhanVien = user.MaNhanVien;
            userVal.HoTen = user.HoTen;
            userVal.MatKhau = user.MatKhau;
            userVal.GioiTinh = user.GioiTinh;

            userVal.MaChucVuNV = user.MaChucVuNV;
            userVal.QueQuan = user.QueQuan;
            userVal.HinhAnh = user.HinhAnh;
            userVal.DanToc = user.DanToc;
            userVal.sdt_NhanVien = user.sdt_NhanVien;
            userVal.MaHopDong = user.MaHopDong;

            userVal.NgaySinh = user.NgaySinh;
            userVal.TrangThai = user.TrangThai;
            userVal.MaChuyenNganh = user.MaChuyenNganh;
            userVal.MaTrinhDoHocVan = user.MaTrinhDoHocVan;
            userVal.MaPhongBan = user.MaPhongBan;

            userVal.CMND = user.CMND;
            userVal.Email = user.Email;
            userVal.Facebookk = user.Facebookk;
            userVal.Bio = user.Bio;
            userVal.XacNhanMatKhau = user.MatKhau;

            return View(userVal);
            //  return View(user);
        }
        [HttpPost]
        public ActionResult EditChuyenNganhNV(UserValidate upUser)
        {
            upUser.XacNhanMatKhau = upUser.MatKhau;
            var us = db.NhanViens.Where(n => n.MaNhanVien == upUser.MaNhanVien).FirstOrDefault();

                //var us = db.NhanViens.Where(n => n.MaNhanVien == upUser.MaNhanVien).FirstOrDefault();
                if (us != null)
                {

                    us.HoTen = upUser.HoTen;
                    us.MatKhau = upUser.MatKhau;
                    us.GioiTinh = upUser.GioiTinh;

                    us.MaChucVuNV = upUser.MaChucVuNV;
                    us.QueQuan = upUser.QueQuan;
                    us.HinhAnh = upUser.HinhAnh;
                    us.DanToc = upUser.DanToc;
                    us.sdt_NhanVien = upUser.sdt_NhanVien;
                    us.MaHopDong = upUser.MaHopDong;

                    us.NgaySinh = upUser.NgaySinh;
                    us.TrangThai = upUser.TrangThai;
                    us.MaChuyenNganh = upUser.MaChuyenNganh;
                    us.MaTrinhDoHocVan = upUser.MaTrinhDoHocVan;
                    us.MaPhongBan = upUser.MaPhongBan;

                    us.CMND = upUser.CMND;
                    us.Email = upUser.Email;
                    us.Facebookk = upUser.Facebookk;
                    us.Bio = upUser.Bio;

                    db.SaveChanges();
                    return Redirect("/admin/QuanLyChuyenNganh");

                
            }
            return View(upUser);

        }//end update
    }
}

QuanLyNhanSu/Areas/admin/Views/QuanLyChuyenNganh/Create.cshtml
@model QuanLyNhanSu.Models.ChuyenNganh

@{
    ViewBag.Title = "Thêm Chuyên Ngành";
}

<h2>Thêm Chuyên Ngành</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.Label("Mã chuyên ngành")
        @Html.TextBoxFor(model => model.MaChuyenNganh, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MaChuyenNganh)
    </div>

    <div class="form-group">
        @Html.Label("Tên chuyên ngành")
        @Html.TextBoxFor(model => model.TenChuyenNganh, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.TenChuyenNganh)
    </div>

    <input type="submit" value="Xác nhận" class="btn btn-primary" />
}

QuanLyNhanSu/Areas/admin/Views/QuanLyChuyenNganh/Delete.cshtml
@model QuanLyNhanSu.Models.ChuyenNganh

@{
    ViewBag.Title = "Xóa Chuyên Ngành";
}

<h2>Xóa Chuyên Ngành</h2>

<h3>Bạn có chắc chắn muốn xóa chuyên ngành này?</h3>
<div>
    <h4>Chuyên Ngành</h4>
    <div>
        <dl class="dl-horizontal">
            <dt>@Html.DisplayName("Mã chuyên ngành")</dt>
            <dd>@Model.MaChuyenNganh</dd>
            <dt>@Html.DisplayName("Tên chuyên ngành")</dt>
            <dd>@Model.TenChuyenNganh</dd>
        </dl>
    </div>
    @using (Html.BeginForm("DeleteConfirmed", "QuanLyChuyenNganh"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MaChuyenNganh)
        <input type="text" name="id" hidden value="@Model.MaChuyenNganh"/>
        <input type="submit" value="Xóa" class="btn btn-danger" />
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-default" })
    
    }
    </div>

QuanLyNhanSu/Areas/admin/Views/QuanLyChuyenNganh/Edit.cshtml
@model QuanLyNhanSu.Models.ChuyenNganh

@{
    ViewBag.Title = "Cập nhật Chuyên Ngành";
}

<h2>Cập nhật Chuyên Ngành</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.MaChuyenNganh)
    <input type="text" hidden name="id" value="@Model.MaChuyenNganh" />
    <div class="form-group">
        @Html.Label("Tên chuyên ngành")
        @Html.TextBoxFor(model => model.TenChuyenNganh, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.TenChuyenNganh)
    </div>

    <input type="submit" value="Xác nhận" class="btn btn-primary" />
}

QuanLyNhanSu/Areas/admin/Views/QuanLyChuyenNganh/EditChuyenNganhNV.cshtml
@{
    ViewBag.Title = "Cập nhật thông tin";
}
<link href="~/Content/css/account.css" rel="stylesheet" />
@using QuanLyNhanSu.Models
@model UserValidate

<!--admin cap nhat-->

<div class="">
    <div class="">
        <h1 class="page-header">
            Cập nhật thông tin nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-fw fa-user"></i><a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>
            </li>
            <li>
                <i class="fa fa-fw fa-user"></i>Cập nhật thông tin nhân viên
            </li>
        </ol>
    </div>
</div>
<div class="">
    <div class=" col-md-6 col-md-offset-3">
        @*@Url.Action("UpdateUser", "QuanLyUser")*@

        @Html.AntiForgeryToken()
        <form class="form-horizontal" method="post" role="form" action="@Url.Action("EditChuyenNganhNV","QuanLyChuyenNganh")">
            @Html.ValidationSummary(true)
            <!--Tai khoang-->
            <div class="form-group">
                <div class="">
                    <div class="col-sm-4 control-label">
                        <label>Tài khoản</label>
                    </div>
                    <div class="col-sm-8">
                        <input type="text" name="MaNhanVien"
                               class="form-control"
                               maxlength="20"
                               value="@Model.MaNhanVien.Trim()"
                               id="MaNhanVien" readonly />
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @ViewBag.MaNhanVien
                        @Html.ValidationMessageFor(n => n.MaNhanVien)
                    </label>

                </div>

            </div>
            <!--ho ten-->
            <div class="form-group">
                <div>
                    <div class="col-sm-4 control-label">
                        <label>Họ tên</label>
                    </div>
                    <div class="col-sm-8">
                        <input type="text" name="HoTen"
                               class="form-control"
                               value="@Model.HoTen"
                               id="HoTen" required readonly />
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(n => n.HoTen)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label  col-md-4 col-sm-4">
                    <label>Chuyên ngành</label>
                </div>
                <div class="col-md-8 col-sm-8">
                    @{
                        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
                        var chuyennganh = db.ChuyenNganhs.ToList();
                    }
                    <select name="MaChuyenNganh" class="form-control">
                        @foreach (var item in chuyennganh)
                        {
                            if (Model.MaChuyenNganh == item.MaChuyenNganh)
                            {
                                <option value="@item.MaChuyenNganh.ToString()" selected>@item.TenChuyenNganh</option>
                            }
                            <option value="@item.MaChuyenNganh.ToString()">@item.TenChuyenNganh</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-4 control-label">Trạng thái</label>
                <div class="col-sm-8">
                    @{
                        string checkActive = string.Empty;
                        string checkInactive = string.Empty;

                        // Check the current value of TrangThai in the Model
                        if (Model.TrangThai == true)
                        {
                            checkActive = "checked";
                        }
                        else
                        {
                            checkInactive = "checked";
                        }
                    }
                    <div class="radio-inline">
                        <label><input type="radio" name="TrangThai" value="True" @checkActive> Hoạt động</label>
                    </div>
                    <div class="radio-inline">
                        <label><input type="radio" name="TrangThai" value="False" @checkInactive> Ngừng hoạt động</label>
                    </div>
                </div>
            </div>

            <div class="hidden">
                <input type="text" name="XacNhanMatKhau" value="@Model.XacNhanMatKhau" />
                <input type="text" name="MatKhau" value="@Model.MatKhau" />
                <input type="text" name="MaTrinhDoHocVan" value="@Model.MaTrinhDoHocVan" />
                <input type="text" name="GioiTinh" value="@Model.GioiTinh" />
                <input type="text" name="QueQuan" value="@Model.QueQuan" />
                <input type="text" name="HinhAnh" value="@Model.HinhAnh" />
                <input type="text" name="DanToc" value="@Model.DanToc" />
                <input type="text" name="sdt_NhanVien" value="@Model.sdt_NhanVien" />
                <input type="text" name="MaHopDong" value="@Model.MaHopDong" />
                <input type="text" name="NgaySinh" value="@Model.NgaySinh" />

                <input type="text" name="Email" value="@Model.Email" />
                <input type="text" name="facebookk" value="@Model.Facebookk" />
                <input type="text" name="Bio" value="@Model.Bio" />
                <input type="text" name="MaPhongBan" value="@Model.MaPhongBan" />
                <input type="text" name="MaChucVuNV" value="@Model.MaChucVuNV" />
                <input type="text" name="CMND" value="@Model.CMND" />

            </div>

            @*button *@
            <div class="form-group">
                <div class=" col-sm-offset-4 col-sm-5">
                    <button type="submit" class="btn btn-primary">Lưu thay đổi</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>

@*@section css{

    }*@

QuanLyNhanSu/Areas/admin/Views/QuanLyChuyenNganh/FindEmployees.cshtml
@model IEnumerable<QuanLyNhanSu.Models.NhanVien>
@{
    ViewBag.Title = "FindEmployees";
    var db = new QuanLyNhanSu.Models.QuanLyNhanSuEntities();
}

<h2>Danh sách nhân viên theo chuyên ngành: @ViewBag.tencn </h2>

<div>
    <h1 class="page-header">Chuyên ngành nhân viên</h1>
    <a class="btn btn-primary" href="@Url.Action("XuatExcel", "QuanLyChuyenNganh")">Thêm Chuyên Ngành</a>
</div>
<hr />
<table id="table-taikhoan" class="table table-bordered table-striped">
    <thead>
        <tr class="success">
            <th>Mã nhân viên</th>
            <th>Mã chuyên ngành</th>
            <th>Tên nhân viên</th>
            <th>Tên chuyên ngành</th>
            <th>Chức vụ</th>
            <th>Trình độ học vấn</th>
            <th>Số lượng: @Model.Count()</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MaNhanVien</td>
                <td>@item.MaChuyenNganh</td>
                <td>@item.HoTen </td>
                <td>@db.ChuyenNganhs.SingleOrDefault(m => m.MaChuyenNganh == item.MaChuyenNganh).TenChuyenNganh </td>
                <td>@db.ChucVuNhanViens.SingleOrDefault(m => m.MaChucVuNV == item.MaChucVuNV).TenChucVu </td>
                <td>@db.TrinhDoHocVans.SingleOrDefault(m => m.MaTrinhDoHocVan == item.MaTrinhDoHocVan).TenTrinhDo </td>
                <td>
                    <a class="btn btn-warning" href="@Url.Action("EditChuyenNganhNV", "QuanLyChuyenNganh", new { id = item.MaNhanVien })">Cập nhật</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-danger" href="/admin/QuanLyChuyenNganh">Back</a>

QuanLyNhanSu/Areas/admin/Views/QuanLyChuyenNganh/Index.cshtml
@model IEnumerable<QuanLyNhanSu.Models.ChuyenNganh>

@{
    ViewBag.Title = "Danh sách chuyên ngành";
}
<div class="">
    <div class="">
        <h1 class="page-header">
            Chuyên ngành nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Chuyên ngành
            </li>
        </ol>
    </div>
</div>
<div>

    <a class="btn btn-primary" href="@Url.Action("Create", "QuanLyChuyenNganh")">Thêm Chuyên Ngành</a>
</div>
<hr />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Mã chuyên ngành</th>
            <th>Tên chuyên ngành</th>
            <th>Số lượng: @Model.Count()</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.MaChuyenNganh</td>
                <td>@item.TenChuyenNganh</td>
                <td>
                    <a class="btn btn-warning" href="@Url.Action("Edit", "QuanLyChuyenNganh", new { id = item.MaChuyenNganh })">Cập nhật</a>
                    <a class="btn btn-danger" href="@Url.Action("Delete", "QuanLyChuyenNganh", new { id = item.MaChuyenNganh })">Xóa</a>
                    <a class="btn btn-info" href="@Url.Action("FindEmployees", "QuanLyChuyenNganh", new { id = item.MaChuyenNganh })">Xem Nhân Viên</a>
                </td>
            </tr>
        }
    </tbody>
</table>