QuanLyNhanSu/Models/ThoiViec.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyNhanSu.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ThoiViec
{

    public string MaNhanVien { get; set; }

    public string Lydo { get; set; }

    public System.DateTime NgayThoiViec { get; set; }

    public string TenNhanVien { get; set; }



    public virtual NhanVien NhanVien { get; set; }

}

}

QuanLyNhanSu/Areas/admin/Controllers/QuanLyUserController.cs
using QuanLyNhanSu.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

//using cExcel = Microsoft.Office.Interop.Excel;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class QuanLyUserController : AuthorController
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        //
        // GET: /admin/QuanLyUser/
        public ActionResult Index(bool? showDisable = false)
        {
            ViewBag.showDisable = showDisable;
            var user = db.NhanViens
                .Where(x => x.MaNhanVien != "admin" && (showDisable == true || x.TrangThai == true))
                .ToList()
                .OrderBy(m => {
                    int id;
                    return int.TryParse(m.MaNhanVien, out id) ? id : int.MaxValue;
                })
                .ToList();
            return View(user);
        }
        [HttpGet]
        public ActionResult Xoa(string id)
        {
            var user = db.NhanViens.SingleOrDefault(x => x.MaNhanVien == id);
            if (user == null)
            {
                return HttpNotFound("Employee not found");
            }

            return View("XoaUser",user);  // Render the XacNhanXoa.cshtml view
        }

        [HttpPost]
        public ActionResult XoaUser(String id,string lydo)
        {
            var employee = db.NhanViens.SingleOrDefault(x => x.MaNhanVien == id);

            var a = db.NhanViens.Where(x => x.MaNhanVien == id).SingleOrDefault();
            var hd = db.HopDongs.Where(x => x.MaHopDong == id).SingleOrDefault();
            var luong = db.Luongs.Where(x => x.MaNhanVien == id).SingleOrDefault();
            var ctLuong = db.ChiTietLuongs.Where(x => x.MaNhanVien == id).ToList();

            // bang mot cach nao do ma tao khong dung remove duoc nen execute bang sql command
            string sql = "INSERT INTO ThoiViecs (MaNhanVien, TenNhanVien, NgayThoiViec, Lydo) VALUES (@MaNhanVien, @TenNhanVien, @NgayThoiViec, @Lydo)";
            db.Database.ExecuteSqlCommand(sql, new SqlParameter("@MaNhanVien", a.MaNhanVien),
                new SqlParameter("@TenNhanVien", a.HoTen),
                new SqlParameter("@NgayThoiViec", DateTime.Now),
                new SqlParameter("@Lydo", lydo));

           /*
            foreach (var item in ctLuong)
            {
                db.ChiTietLuongs.Remove(item);
            }

            db.Luongs.Remove(luong);
            db.NhanViens.Remove(a);
            */
            db.HopDongs.Remove(hd);

         
            db.SaveChanges();
            return Redirect("~/admin/QuanLyUser");
        }
        [HttpGet]
        public ActionResult UpdateUser(String id)
        {
            var user = db.NhanViens.Where(n => n.MaNhanVien == id).FirstOrDefault();
            UserValidate userVal = new UserValidate();

            userVal.MaNhanVien = user.MaNhanVien;
            userVal.HoTen = user.HoTen;
            userVal.MatKhau = user.MatKhau;
            userVal.GioiTinh = user.GioiTinh;

            userVal.MaChucVuNV = user.MaChucVuNV;
            userVal.QueQuan = user.QueQuan;
            userVal.HinhAnh = user.HinhAnh;
            userVal.DanToc = user.DanToc;
            userVal.sdt_NhanVien = user.sdt_NhanVien;
            userVal.MaHopDong = user.MaHopDong;

            userVal.NgaySinh = user.NgaySinh;
            userVal.TrangThai = user.TrangThai;
            userVal.MaChuyenNganh = user.MaChuyenNganh;
            userVal.MaTrinhDoHocVan = user.MaTrinhDoHocVan;
            userVal.MaPhongBan = user.MaPhongBan;

            userVal.CMND = user.CMND;
            userVal.Email = user.Email;
            userVal.Facebookk = user.Facebookk;
            userVal.Bio = user.Bio;
            userVal.XacNhanMatKhau = user.MatKhau;

            return View(userVal);
            //  return View(user);
        }
        [HttpPost]
        public ActionResult UpdateUser(UserValidate upUser)
        {
            upUser.XacNhanMatKhau = upUser.MatKhau;
            var us = db.NhanViens.Where(n => n.MaNhanVien == upUser.MaNhanVien).FirstOrDefault();

            if (ModelState.IsValid)
            {
                //var us = db.NhanViens.Where(n => n.MaNhanVien == upUser.MaNhanVien).FirstOrDefault();
                if (us != null)
                {

                    CapNhatTrinhDoHocVan capNhat = new CapNhatTrinhDoHocVan();
                    capNhat.MaNhanVien = upUser.MaNhanVien;
                    capNhat.NgayCapNhat = DateTime.Now.Date;
                    capNhat.MaTrinhDoTruoc = us.MaTrinhDoHocVan;
                    capNhat.MaTrinhDoCapNhat = upUser.MaTrinhDoHocVan;

                    us.MaNhanVien = upUser.MaNhanVien;
                    us.HoTen = upUser.HoTen;
                    us.MatKhau = upUser.MatKhau;
                    us.GioiTinh = upUser.GioiTinh;

                    us.MaChucVuNV = upUser.MaChucVuNV;
                    us.QueQuan = upUser.QueQuan;
                    us.HinhAnh = upUser.HinhAnh;
                    us.DanToc = upUser.DanToc;
                    us.sdt_NhanVien = upUser.sdt_NhanVien;
                    us.MaHopDong = upUser.MaHopDong;

                    us.NgaySinh = upUser.NgaySinh;
                    us.TrangThai = upUser.TrangThai;
                    us.MaChuyenNganh = upUser.MaChuyenNganh;
                    us.MaTrinhDoHocVan = upUser.MaTrinhDoHocVan;
                    us.MaPhongBan = upUser.MaPhongBan;
                    
                    us.CMND = upUser.CMND;
                    us.Email = upUser.Email;
                    us.Facebookk = upUser.Facebookk;
                    us.Bio = upUser.Bio;

                    var trinhdo = db.TrinhDoHocVans.Where(n => n.MaTrinhDoHocVan.Equals(us.MaTrinhDoHocVan)).FirstOrDefault();

                    var luong = db.Luongs.Where(n => n.MaNhanVien.Equals(us.MaNhanVien)).FirstOrDefault();

                    if (trinhdo.HeSoBac != null)
                    {
                        luong.HeSoLuong = luong.HeSoLuong < (double)trinhdo.HeSoBac ? (double)trinhdo.HeSoBac : luong.HeSoLuong;
                    }
                    else
                    { luong.HeSoLuong = 1; }



                    db.CapNhatTrinhDoHocVans.Add(capNhat);

                    db.SaveChanges();
                    return Redirect("/admin/QuanLyUser");

                }
            }
            return View(upUser);

        }//end update

        [HttpGet]

        public ActionResult ThemUser()
        {
            var lastEmployee = db.NhanViens
    .Where(x => x.MaNhanVien != "Admin") 
    .OrderByDescending(x => x.MaNhanVien.Length)
    .ThenByDescending(x => x.MaNhanVien) 
    .FirstOrDefault();
            if (lastEmployee != null)
            {
                var numericPart = int.Parse(lastEmployee.MaNhanVien);
                string nextMaNhanVien = (numericPart + 1).ToString();
                ViewBag.NextMaNhanVien = nextMaNhanVien;
            }
            else
            {
                ViewBag.NextMaNhanVien = null;
            }
            var chucvu = db.ChucVuNhanViens.ToList();
            var phongban = db.PhongBans.ToList();
            var hopdong = db.HopDongs.ToList();
            var chuyennganh = db.ChuyenNganhs.ToList();
            var trinhdo = db.TrinhDoHocVans.ToList();
            List<ChucVuNhanVien> list = chucvu;

            return View(new UserValidate());
        }


        [HttpPost]
        public ActionResult ThemUser(UserValidate nv)
        {

            nv.XacNhanMatKhau = nv.MatKhau;
            if (ModelState.IsValid)
            {
                ViewBag.err = String.Empty;
                var checkMaNhanVien = db.NhanViens.Any(x => x.MaNhanVien == nv.MaNhanVien);

                if (checkMaNhanVien)
                {
                    ViewBag.err = "tài khoản đã tồn tại";
                    //ModelState.AddModelError("MaNhanVien", "Mã tài khoản đã tồn tại");
                    return View(nv);
                }
                else
                {
                    Luong luong = new Luong();
                    HopDong hd = new HopDong();
                    NhanVien nvAdd = new NhanVien();
                    nvAdd.MaNhanVien = nv.MaNhanVien;
                    nvAdd.MatKhau = nv.MatKhau;
                    nvAdd.HoTen = nv.HoTen;
                    nvAdd.NgaySinh = nv.NgaySinh;
                    nvAdd.QueQuan = nv.QueQuan;
                    nvAdd.GioiTinh = nv.GioiTinh;
                    nvAdd.DanToc = nv.DanToc;
                    nvAdd.MaChucVuNV = nv.MaChucVuNV;
                    nvAdd.MaPhongBan = nv.MaPhongBan;
                    nvAdd.MaChuyenNganh = nv.MaChuyenNganh;
                    nvAdd.MaTrinhDoHocVan = nv.MaTrinhDoHocVan;
                    nvAdd.MaHopDong = nv.MaNhanVien;
                    nvAdd.TrangThai = true;
                    nvAdd.HinhAnh = "icon.jpg";

                    //add hop dong
                    hd.MaHopDong = nv.MaNhanVien;
                    hd.NgayBatDau = DateTime.Now.Date;

                    //tao bang luong
                    luong.MaNhanVien = nv.MaNhanVien;
                    luong.LuongToiThieu = 1150000;
                    luong.BHXH = 8;
                    luong.BHYT = 1.5;
                    luong.BHTN = 1;
                    var trinhdo = db.TrinhDoHocVans.Where(n => n.MaTrinhDoHocVan.Equals(nv.MaTrinhDoHocVan)).FirstOrDefault();
                    var chucvu = db.ChucVuNhanViens.Where(n => n.MaChucVuNV.Equals(nv.MaChucVuNV)).SingleOrDefault();

                    if (trinhdo.MaTrinhDoHocVan.Equals(nv.MaTrinhDoHocVan))
                    {
                        luong.HeSoLuong = (double)trinhdo.HeSoBac;
                    }


                    if (chucvu.MaChucVuNV.Equals(nv.MaChucVuNV))
                    {

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/Index.cshtml
@using QuanLyNhanSu.Models
@model List<NhanVien>

@{
    ViewBag.Title = "Nhân viên";
}
@{
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
    var td = db.TrinhDoHocVans.ToList();
    string trangthai;
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-user"></i> Nhân viên
            </li>
        </ol>
    </div>
</div>

<div>
    <div style="padding:10px">
        <a class="btn btn-primary" href="@Url.Action("ThemUser", "QuanLyUser")">
            Thêm nhân viên
        </a>

        <a class="btn btn-primary " href="@Url.Action("XuatFileExel", "QuanLyUser")">
            Xuất danh sách nhân viên
        </a>
        <a class="btn btn-primary" href="@Url.Action("Index", "QuanLyUser", new { showDisable = !(ViewBag.showDisable ?? false) })">
            Hiện nhân viên đã ngừng hoạt động
        </a>
        <a class="btn btn-primary" href="@Url.Action("ThoiViec", "QuanLyUser", new { thoiviec = !(ViewBag.ThoiViec ?? false) })">
            Nhân viên thôi việc
        </a>
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Avatar
                </th>
                <th>
                    Mã nhân viên
                </th>
                <th>
                    Họ tên
                </th>
                <th>
                    Trình độ văn hóa
                </th>
                <th>
                    Giới tính
                </th>
                <th>
                    Ngày bắt đầu
                </th>
                <th>
                    Trạng thái
                </th>
                <th>
                    Số lượng: @Model.Count
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model)
                {
                    string tenTrinhDo = string.Empty;
                    string gioitinh = string.Empty;
                    switch (item.GioiTinh)
                    {
                        case 0:
                            gioitinh = "Nữ";
                            break;
                        case 1:
                            gioitinh = "Nam";
                            break;
                        default:
                            gioitinh = "Khác";
                            break;
                    }

                    foreach (var t in td)
                    {
                        if (t.MaTrinhDoHocVan.Equals(item.MaTrinhDoHocVan))
                        {
                            tenTrinhDo = t.TenTrinhDo;
                            break;
                        }
                    }

                    <tr>
                        <td>
                            @if (!string.IsNullOrEmpty(item.HinhAnh))
                            {
                                <img src="~/Content/images/@item.HinhAnh" alt="Avatar" style="width: 50px; height: 50px; border-radius: 50%;" />
                            }
                            else
                            {
                                <img src="~/Content/images/default-avatar.png" alt="Default Avatar" style="width: 50px; height: 50px; border-radius: 50%;" />
                            }
                        </td>
                        <td>@item.MaNhanVien</td>
                        <td>@item.HoTen</td>
                        <td>@tenTrinhDo</td>
                        <td>@gioitinh</td>
                        <td>
                                @String.Format("{0:dd/MM/yyyy}", @item.HopDong.NgayBatDau)
                            @{ 
                                DateTime ngaydau = Convert.ToDateTime(@item.HopDong.NgayBatDau);
                                DateTime ngaysau = DateTime.Now.Date;
                                TimeSpan Times = ngaysau - ngaydau;

                                int sonam = (int)Times.Days / 365;
                            }

                        </td>
                        <td>
                            @{ 
                                switch (item.TrangThai)
                                {
                                    case true:
                                        trangthai = "Hoạt động";
                                        break;
                                    case false:
                                        trangthai = "Ngưng hoạt động";
                                        break;
                                    default:
                                        trangthai = "hên xui";
                                        break;
                                }
                                
                            }
                            @trangthai
                        </td>
                        <td>
                            <a class="btn btn-primary" href="@Url.Action("QuaTrinhCongTac", "QuanLyUser", new { id = item.MaNhanVien })">
                                <i class="fa fa-address-book"></i> Quá trình công tác
                            </a>
                            <a class="btn btn-info" href="@Url.Action("QuaTrinhHoc", "QuanLyUser", new { id = item.MaNhanVien })">
                                Học vấn
                            </a>
                            <a class="btn btn-warning" href="@Url.Action("UpdateUser", "QuanLyUser", new { id = item.MaNhanVien })">
                                <i class="fa fa-pencil-square-o x5" aria-hidden="true"></i> Sửa
                            </a>
                            <a class="btn btn-danger" href="@Url.Action("Xoa", "QuanLyUser", new { id = item.MaNhanVien })">
                                <i class="fa fa-trash-o"></i> Xóa
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/QuaTrinhCongTac.cshtml
@using QuanLyNhanSu.Models
@model List<LuanChuyenNhanVien>

@{
    ViewBag.Title = "Quá trình công tác";
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Quá trình công tác
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-fw fa-tasks"></i><a href="@Url.Action("index","QuanLyPhongBan")">Phòng ban</a>
            </li>
            <li>
                <i class="fa fa-bar-chart-o"></i> <a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>
            </li>
        </ol>
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên
                </th>
                <th>
                    Phòng ban cũ
                </th>
                <th>
                    Phòng ban chuyển đến
                </th>
                <th>
                    Lý do
                </th>
                <th>
                    Ngày chuyển
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhanVien.MaNhanVien)
                    </td>
                    @{
                QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
                String chuyendi = String.Empty;
                String chuyenden = String.Empty;
                foreach (var pb in db.PhongBans)
                {
                    if (pb.MaPhongBan.Equals(item.PhongBanChuyen))
                    {
                        chuyendi = pb.TenPhongBan;
                    }
                    if (pb.MaPhongBan.Equals(item.PhongBanDen))
                    {
                        chuyenden = pb.TenPhongBan;
                    }

                }
                    }
                    <td>
                        @chuyendi
                    </td>
                    <td>
                        @chuyenden
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LyDoChuyen)
                    </td>
                    <td>
                        @string.Format("{0:dd/MM/yyyy}", item.NgayChuyen)
                    </td>


                </tr>
            }
        </tbody>

    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/QuaTrinhHoc.cshtml
@*@model IEnumerable<QuanLyNhanSu.Models.CapNhatTrinhDoHocVan>*@
@using QuanLyNhanSu.Models
@model List<CapNhatTrinhDoHocVan>
@{
    ViewBag.Title = "Học vấn";
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
}


<div class="">
    <div class="">
        <h1 class="page-header">
            Quá trình học
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-fw fa-tasks"></i><a href="@Url.Action("index","QuanLyPhongBan")">Phòng ban</a>
            </li>
            <li>
                <i class="fa fa-bar-chart-o"></i> <a href="@Url.Action("index","QuanLyUser")">Nhân viên</a>
            </li>
        </ol>
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Họ tên
                </th>
                <th>
                    Chuyên ngành
                </th>
                <th>
                    Trình độ trước
                </th>
                <th>
                    Trình độ mới
                </th>
                <th>
                    Ngày cập nhật
                </th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhanVien.HoTen)
                    </td>

                    @{
                String cn = String.Empty;
                foreach (var c in db.ChuyenNganhs)
                {
                    if (@item.NhanVien.MaChuyenNganh == c.MaChuyenNganh)
                    {
                        cn = c.TenChuyenNganh;
                    }
                }
                    }
                    <td>@cn</td>
                    @{
                String t = String.Empty;
                String s = String.Empty;

                foreach (var hv in db.TrinhDoHocVans)
                {

                    if (item.MaTrinhDoTruoc == hv.MaTrinhDoHocVan)
                    {
                        t = hv.TenTrinhDo;
                    }
                    if (item.MaTrinhDoCapNhat == hv.MaTrinhDoHocVan)
                    {
                        s = hv.TenTrinhDo;
                    }
                }
                    }
                    <td>
                        @t
                    </td>
                    <td>
                        @s
                    </td>

                    <td>
                        @String.Format("{0:dd/MM/yyyy}", @item.NgayCapNhat)
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/ThoiViec.cshtml
@using QuanLyNhanSu.Models
@model IEnumerable<QuanLyNhanSu.Models.ThoiViec>

@{
    ViewBag.Title = "Nhân viên";
}
@{
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();

}

<div class="">
    <div class="">
        <h1 class="page-header">
            Nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-user"></i> Nhân viên
            </li>
        </ol>
    </div>
</div>

<div>
    <div style="padding:10px">
        <a class="btn btn-primary" href="@Url.Action("ThemUser", "QuanLyUser")">
            Thêm nhân viên
        </a>

        <a class="btn btn-primary " href="@Url.Action("XuatFileExel", "QuanLyUser")">
            Xuất danh sách nhân viên
        </a>
        <a class="btn btn-primary" href="@Url.Action("Index", "QuanLyUser", new { showDisable = !(ViewBag.showDisable ?? false) })">
            Hiện nhân viên đã ngừng hoạt động
        </a>
        <a class="btn btn-primary" href="@Url.Action("ThoiViec", "QuanLyUser", new { thoiviec = !(ViewBag.ThoiViec ?? false) })">
            Nhân viên thôi việc
        </a>
    </div>
</div>

<div class="table-responsive">
    <table id="table-taikhoan" class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên cũ
                </th>
                <th>
                    Họ tên
                </th>
                <th>
                    Lý do thôi việc
                </th>
                <th>
                    Ngày thôi việc
                </th>
                <th>
                    Số lượng: @Model.Count()
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaNhanVien</td>
                        <td>@item.TenNhanVien</td>
                        <td>@item.Lydo</td>
                        <td>@item.NgayThoiViec</td>
                        <td>
                            <a class="btn btn-danger" href="@Url.Action("XoaThoiViec", "QuanLyUser", new { id = item.MaNhanVien, name=item.TenNhanVien})">
                                <i class="fa fa-trash-o"></i> Xóa dữ liệu
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyUser/XoaUser.cshtml
@model QuanLyNhanSu.Models.NhanVien

@{
    ViewBag.Title = "Xác nhận xóa nhân viên";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa nhân viên</h2>

<div class="alert alert-danger">
    <h4>Bạn có chắc chắn muốn đuổi nhân viên này không?</h4>
    <h5>Mọi thông tin liên quan đến @Model.HoTen đều bị xóa bỏ.</h5>
</div>

<div class="form-horizontal">
    <h4>Chi tiết nhân viên:</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>Mã nhân viên:</dt>
        <dd>@Model.MaNhanVien</dd>

        <dt>Tên nhân viên:</dt>
        <dd>@Model.HoTen</dd>

        <dt>Giới tính:</dt>
        <dd>@Model.GioiTinh</dd>

        <dt>Ngày sinh:</dt>
        <dd>@Model.NgaySinh.ToString()</dd>

        <dt>Địa chỉ:</dt>
        <dd>@Model.QueQuan</dd>

        <dt>Số điện thoại:</dt>
        <dd>@Model.sdt_NhanVien</dd>

        <dt>Email:</dt>
        <dd>@Model.Email</dd>
    </dl>
</div>
@using (Html.BeginForm("XoaUser", "QuanLyUser", FormMethod.Post))
{
    @Html.HiddenFor(model => model.MaNhanVien)
    @Html.AntiForgeryToken()

<div class="form-actions">
    <div>
        <label for="lydo">Lý do thôi việc:</label>
        <textarea name="lydo" id="lydo" required class="form-control" style="width: 100%; height: 100px;"></textarea>
    </div>
    <input type="text" hidden value="@Model.MaNhanVien" name="id" />
    <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
    @Html.ActionLink("Hủy bỏ", "Index", null, new { @class = "btn btn-default" })
    <a href="@Url.Action("NgungHoatDong", "QuanLyUser", new { id = Model.MaNhanVien })" class="btn btn-warning" title="Nhân viên sẽ không đi vào hoạt động nhân vẫn giữ thông tin">Ngưng hoạt động</a>
</div>
}